### ISSUE TITLE
Social media post submission system for SR teams

### ISSUE THREAD

**Issue by sedders123** [srobo/marketing-team-minutes#11]
From https://github.com/srobo/competition-team-minutes/blob/master/2021/2021-08-31.md#specific

**Comment by antoinepetty** [comment]
Using github issue templates seems like a good solution to this 

e.g. https://github.com/srobo/kit-logistics/issues

**Comment by sedders123** [comment]
https://resoc.io/ looks like it could be useful to us

**Comment by sedders123** [comment]
https://github.com/srobo/social-media-posts Now exists, we can iterate from there
