### ISSUE TITLE
Decide on SR youtube channel url

### ISSUE THREAD

**Issue by antoinepetty** [srobo/marketing-team-minutes#17]
Can't be changed once set
Suggested: https://www.youtube.com/c/StudentRobotics

**Comment by antoinepetty** [comment]
We already have https://www.youtube.com/user/studentrobotics/ which won't change

**Comment by PeterJCLaw** [comment]
Note also that (presumably for legacy reasons) https://www.youtube.com/StudentRobotics is ours too (redirects to https://www.youtube.com/user/studentrobotics).

**Comment by antoinepetty** [comment]
If we have /studentrobotics anyway it's probably not worth choosing the /c/ version then
I think it's worth just leaving it as is
