### ISSUE TITLE
Arrange Adventurous Machines sponsored post

### ISSUE THREAD

**Issue by sedders123** [srobo/marketing-team-minutes#31]
From https://github.com/srobo/marketing-team-minutes/blob/master/2021/2021-12-02.md#specific

**Comment by antoinepetty** [comment]
cc fundraising

**Comment by sedders123** [comment]
Sent initial email reaching out to Adventurous Machines about their post

**Comment by antoinepetty** [comment]
This is scheduled

**Comment by sedders123** [comment]
Was posted yesterday
