### ISSUE TITLE
Write SR2021 Annual Report 

### ISSUE THREAD

**Issue by antoinepetty** [srobo/marketing-team-minutes#34]
Requested by trustees

This is a short report to cover the year to July 2021 with the following headings: 
your charity’s name, registration number, address and trustee names
its structure and details of how it is managed, including how it recruits trustees
its activities and objectives in the year
its achievements and performance, including reporting on its public benefit

**Comment by sedders123** [comment]
First Draft has been sent to Trustees. Comments made and are being actioned

**Comment by sedders123** [comment]
This has been submitted https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5054803/accounts-and-annual-returns
