### ISSUE TITLE
Create competition booklet

### ISSUE THREAD

**Issue by antoinepetty** [srobo/marketing-team-minutes#37]
This is a booklet of a few pages which describes Student Robotics for anyone visiting the competition. It's essentially a paper version of the website

**Comment by Scarzy** [comment]
My expectation would be for this to be far more event based than a paper
version of the website. The aim being that anyone coming through the door
understands what they are looking at, be that a stranger who just thinks
"Oh, this looks cool, let's have a nose around", a parent of a competitor
who wants to find their child , or a team who want to know their opponent
(and need to see the list of sponsors). Most of these don't need to know
much about how SR operates.

As a very rough breakdown of what I would expect to see would be (in no
particular order):

   - What is SR? (2 sides absolute max)
   - What is the game?
   - Who are the teams (TLA to real name, and maybe a 1-2 line bio at most)
   - Sponsors
   - A map
   - How to find help if needed (both volunteer support, and first aid etc.)

Feel free to tell me I'm wrong, but most of the website is more about
attracting teams and sponsors, which in my mind isn't really what the
competition booklet needs to do

**Comment by antoinepetty** [comment]
Thanks Scarzy!

Here's the SR2019 booklet as an example for whoever takes on this task: https://github.com/srobo/competitor-booklet-2019/releases/tag/SR2019

**Comment by Scarzy** [comment]
v2.2 is currently in slack for review

**Comment by sedders123** [comment]
These have now arrived see https://github.com/srobo/tasks/issues/744 and https://github.com/srobo/tasks/issues/745
