### ISSUE TITLE
Design & Order banner

### ISSUE THREAD

**Issue by antoinepetty** [srobo/marketing-team-minutes#38]
big banner for photos
![image](https://user-images.githubusercontent.com/36314396/149841604-3e493be9-dd1f-4078-9574-2270697d5d17.png)

**Comment by sedders123** [comment]
https://github.com/srobo/promotional-material/blob/master/banner/banner.svg

**Comment by samjmartin04** [comment]
https://www.bannerworld.co.uk/product/premium-pvc-banner-printing/ seems reasonable. £86.40 for a 6m by 1m banner (2019 banner seems to be 6mx1m)

**Comment by antoinepetty** [comment]
Designed but printing is blocked on IET approval https://github.com/srobo/promotional-material/pull/15

**Comment by antoinepetty** [comment]
Ordered the banner but forgot to add eyelets 🤦‍♂️
Ringing them in the morning to change it if possible

**Comment by antoinepetty** [comment]
Banner has arrived
