### ISSUE TITLE
Get monochrome versions of sponsor logos for tshirts

### ISSUE THREAD

**Issue by antoinepetty** [srobo/marketing-team-minutes#43]
The logos shown on our website probably wouldn't be suitable for tshirts

**Comment by antoinepetty** [comment]
Have asked ITDev

**Comment by antoinepetty** [comment]
ITDev sent us one

**Comment by sedders123** [comment]
Need a monochrome logo for Systemettric. We also need to reach out to Adventurous Machines to confirm they are happy for their logo to be just one colour (white)

**Comment by sedders123** [comment]
Decided we're happy with Systemetric as it's one colour

**Comment by antoinepetty** [comment]
Adventurous Machines are happy with us converting theirs to white

**Comment by antoinepetty** [comment]
We've converted the remaining logos to white ourselves. Just waiting on approval from IET

**Comment by sedders123** [comment]
IET have given approval
