### ISSUE TITLE
Find out IET marketing expectations

### ISSUE THREAD

**Issue by antoinepetty** [srobo/marketing-team-minutes#47]
Our agreement with the IET is very specific so we should make sure we know which branding to include etc

**Comment by sedders123** [comment]
Have asked Scarzy to send over the Publication Guidelines mentioned in the contract

**Comment by sedders123** [comment]
Have scheduled a gentle chase email

**Comment by antoinepetty** [comment]
We have a response and documentation. We need to use both the IET and IMechE Logos on pretty much anything where other sponsors appear and also gain their approval before publishing
