### ISSUE TITLE
Reach out to sponsors about video for tech day

### ISSUE THREAD

**Issue by antoinepetty** [srobo/marketing-team-minutes#48]
Sponsor thing listed on website for Silver+: An opportunity during the year to present your organisation to our student competitors

**Comment by antoinepetty** [comment]
We'll collaborate with fundraising team for the requirements of this

**Comment by sedders123** [comment]
Think this is a matter for the fundraising team and competition team? If these videos need to be shared publicly we'll happily get involved though
