### ISSUE TITLE
Look at websites belonging to similar organisations for inspiration

### ISSUE THREAD

**Issue by sedders123** [srobo/marketing-team-minutes#5]
We should look at other similar organisations websites to see if there is anything that we are missing or if there are ideas we can borrow to help ensure our website is as useful as possible to our varied user types (sponsors, public, competitors, team leaders, volunteers).

**Comment by antoinepetty** [comment]
I think the list from the website meeting minutes was a curated list from my original search:
https://www.firstinspires.org/robotics/frc
https://www.greenpower.co.uk/
https://materovcompetition.org/
https://www.raspberrypi.org/support-us/
