### ISSUE TITLE
Change github logo to not have transparent background within blue circle

### ISSUE THREAD

**Issue by antoinepetty** [srobo/marketing-team-minutes#53]
It looks bad on dark mode
![image](https://user-images.githubusercontent.com/36314396/167011787-c08b7518-ea86-4187-99af-1280dbee5320.png)

**Comment by RealOrangeOne** [comment]
It's very often we find outselves wanting a transparently-backed circle, but with the white innerds. This would be great to put an SVG version of that in a reusable place.

**Comment by raccube** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/6197148/219978155-c4f5d38f-d4ac-4bb8-905f-b180aec9f192.png">
Updated!
