### ISSUE TITLE
Upload video of SR2022 final

### ISSUE THREAD

**Issue by antoinepetty** [srobo/marketing-team-minutes#55]
I have a video and Dan has one too. We should splice those together for a video like what we did in SR2019 https://www.youtube.com/watch?v=gOeP96OngE0

**Comment by antoinepetty** [comment]
If it's interesting enough, we could replace the 2013 video on https://studentrobotics.org/compete/

**Comment by sedders123** [comment]
@antoinepetty did this 🎉
